Add thread safety to metrics context
temporalio/temporal pull request #1517
Opened 2021-05-03 18:35 UTC by Ardagan

**What changed?**
Add thread safety to metrics context.

**Why?**
We report metrics in multiple threads.

**How did you test it?**
manual/auto tests

**Potential risks**
Performance

**Is hotfix candidate?**
No

2021-05-03 20:28 UTC, wxing1292 commented on common/metrics/grpc.go
> +		CountersInt *sync.Map
some blogs says sync.Map is slow, can you do a bench?
my guess, sync.Map can be performant if there are tons of concurrent read and write, which is not this use case

2021-05-03 20:28 UTC, wxing1292 requested changes
plz do a bench test

2021-05-04 17:27 UTC, wxing1292 commented on common/metrics/grpc.go
> +	result, _ := metricsBaggage.CountersInt[name]
lock?

2021-05-04 18:56 UTC, alexshtin approved these changes

2021-05-04 20:29 UTC, wxing1292 approved these changes

2021-05-04 20:52 UTC, merged