Add option to specify custom metrics reporter
temporalio/temporal pull request #1561
Opened 2021-05-20 20:14 UTC by Ardagan

**What changed?**
WithCustomMetricsReporter now can also set generic custom reporter for metrics.

**Why?**
Extensibility point for metrics.

**How did you test it?**
Automated tests, manual testing.

**Potential risks**
N/A

**Is hotfix candidate?**
No

2021-05-21 16:33 UTC, alexshtin commented on common/metrics/config.go
> +		} else {
```suggestion
		}
```

2021-05-21 16:33 UTC, alexshtin commented on common/metrics/config.go
> +		}
```suggestion
```

2021-05-21 16:41 UTC, alexshtin requested changes

2021-05-21 16:41 UTC, alexshtin commented on common/metrics/config.go
> +func (c *Config) initReporterFromPrometheusConfig(logger log.Logger, config *PrometheusConfig, customReporter interface{}) (Reporter, error) {
This name is wrong now as it has nothing to do with `PrometheusConfig` in case if `customReporter` is passed.

2021-05-21 16:41 UTC, alexshtin commented on temporal/server_option.go
> +func WithCustomMetricsReporter(reporter interface{}) ServerOption {
Should you add TODO saying to change parameter type to `Reporter` when tally is removed?

2021-05-21 16:41 UTC, alexshtin commented on common/metrics/config.go
> +			err := fmt.Errorf("customReporter is not of metrics.Reporter type when %s framework type is specified",
```suggestion
			err := fmt.Errorf("customReporter doesn't implement metrics.Reporter interface when %s framework type is specified",
```

2021-05-21 16:41 UTC, alexshtin commented on common/metrics/config.go
> +	FrameworkCustom = "custom"
I wouldn't add this. Just completely ignore config if custom reporter is not `nil` in server options.

2021-05-21 21:42 UTC, wxing1292 approved these changes

2021-05-22 01:24 UTC, alexshtin approved these changes

2021-05-24 18:04 UTC, merged