Add CloseShard to persistence interface
temporalio/temporal pull request #2154
Opened 2021-11-09 03:48 UTC by dnr

**What changed?**

History notifies persistence when it's unloading a shard

**Why?**

**How did you test it?**

Will add unit test if this looks good

**Potential risks**

**Is hotfix candidate?**

2021-11-09 04:02 UTC, yiminc approved these changes

2021-11-09 04:23 UTC, yiminc requested changes
please double check with @wxing1292

2021-11-09 17:23 UTC, paulnpdev commented on common/persistence/dataInterfaces.go
> +	CloseShardRequest struct {
Personally I wish we didn't have a proto for every single little thing we do.  RequestShardAction with an enum for the action type would be a lot cleaner imo, but I'm pretty sure that ship has sailed :)  Just kvetching.

2021-11-09 17:23 UTC, paulnpdev commented on common/persistence/shard_manager.go
> +	return m.shardStore.CloseShard(internalRequest)
Need to understand, decide, and document what are the concurrency semantics here.   Are you expecting this fn to block until the shard is *really* closed?  Or do we use this to trigger shard shutdown and allow it to proceed in the background?  Should we convey to the persistence layer whether we want an immediate shutdown or a graceful one?  Should that be a hint or a command?  Needs a bit of discussion (including @wxing1292  @yiminc )

2021-11-09 17:23 UTC, paulnpdev commented on common/persistence/sql/shard.go
> +func (m *sqlShardStore) CloseShard(
does this PR need to include an implementation for Cassandra, MySQL, etc.?  Or does this line provide a default impl?

2021-11-11 01:04 UTC, dnr commented
Going to do something different here

2021-11-11 01:04 UTC, closed without merging