Add DeleteNamespace API to workflowservice
temporalio/temporal pull request #2185
Opened 2021-11-17 01:58 UTC by alexshtin

- First version
- Namespace validator
- Fix merge errors
- Update clients
- Add DeleteNamespace to integration tests
- Add unit tests

**What changed?**

**Why?**

**How did you test it?**

**Potential risks**

**Is hotfix candidate?**

2021-11-17 02:41 UTC, wxing1292 commented on common/metrics/defs.go
> +		FrontendClientDeleteNamespaceScope:                    {operation: "FrontendClientDeleteNamespace", tags: map[string]string{ServiceRoleTagName: FrontendRoleTagValue}},
@feedmeapples is migrating namespace APIs to admin side, so should this API be also moved to admin side?

2021-11-20 01:14 UTC, yiminc approved these changes

2021-11-21 00:32 UTC, yiminc requested changes
Should we consider alternative: one API to update namespace state that would work for Deprecate/Delete/Handover and any new state we may introduce in future? 
We just need to add one extra field `state` (default UNSPECIFIED) to existing [proto UpdateNamespaceInfo](https://github.com/temporalio/api/blob/a80e5aa7ff23b46ba22e074893983cc452c0b79f/temporal/api/namespace/v1/message.proto#L73)

2021-11-21 16:34 UTC, paulnpdev commented
How about introducing a "NamespaceState" that includes a Deleted state.  This would allow us to offer a reasonable Undo capability, which would be very useful for self-service namespaces (if not required).  And it would simplify the model a lot.  You only need one interface!  Albeit with slightly more complex options.  But I think there' s a lot of bang for the buck here.  And it would make it easy to introduce new states for future enhancements in a backwardsly compatible manner.  Namespaces are critical ... maybe some others might have an opinion here about future needs: @mfateev, @samarabbas, @rylandg

2021-11-23 06:06 UTC, yiminc commented
I assume @alexshtin agreed with my proposal as he stamped the PR to update [api PR](https://github.com/temporalio/api/pull/129/files)

2021-12-02 23:20 UTC, yiminc approved these changes

2021-12-03 02:02 UTC, merged