Move DeleteWorkflowExecution to workflow service
temporalio/temporal pull request #3300
Opened 2022-09-02 00:32 UTC by alexshtin

**What changed?**
Move `DeleteWorkflowExecution` to workflow service.

**Why?**
https://github.com/temporalio/api/pull/233.

**How did you test it?**
Existing tests.

**Potential risks**
Move is a breaking change, exiting clients that use `DeleteWorkflowExecution` will stop to work, but this API is used by `tctl v2` only which is in beta.

**Is hotfix candidate?**
No.

2022-09-02 01:06 UTC, yiminc requested changes
Your PR mixed with batch operation change. I think you need to rebase to latest master.

2022-09-02 01:06 UTC, yiminc commented on service/frontend/dcRedirectionHandler.go
> +func (handler *DCRedirectionHandlerImpl) StartBatchOperation(
did you mess up your commit history or do you have to rebase to latest master? This should no appear in your PR.

2022-09-06 18:19 UTC, alexshtin commented on common/metrics/defs.go
> +		FrontendDeleteWorkflowExecutionScope:            {operation: "FrontendDeleteWorkflowExecution"},
:man_facepalming:

2022-09-07 00:17 UTC, yiminc approved these changes

2022-09-07 01:46 UTC, merged