Move interfaces to one package avoiding go circular imports
temporalio/temporal pull request #3592
Opened 2022-11-14 20:53 UTC by wxing1292

**What changed?**
* Move top level history service interface def to one package avoiding unnecessary go circular imports

**Why?**
See above

**How did you test it?**
N/A

**Potential risks**
N/A

**Is hotfix candidate?**
N/A

2022-11-14 22:23 UTC, paulnpdev approved these changes

2022-11-14 22:40 UTC, rodrigozhou approved these changes
Isn't `defs` more standard name for this instead of `definition`? No strong opinion though.

Left some nit comments in the code.

2022-11-14 22:40 UTC, rodrigozhou commented on service/history/definition/event_notifier.go
> +//go:generate mockgen -copyright_file ../../../LICENSE -package $GOPACKAGE -source $GOFILE -destination event_notifier_mock.go
Move this to right after the license, before the package name line.

2022-11-14 22:40 UTC, rodrigozhou commented on service/history/definition/event_cache.go
> +//go:generate mockgen -copyright_file ../../../LICENSE -package $GOPACKAGE -source $GOFILE -destination event_cache_mock.go
Move this to right after the license, before the package name line.

2022-11-14 22:40 UTC, rodrigozhou commented on service/history/definition/shard_context.go
> +//go:generate mockgen -copyright_file ../../../LICENSE -package $GOPACKAGE -source $GOFILE -destination shard_context_mock.go
ditto

2022-11-14 22:40 UTC, rodrigozhou commented on service/history/definition/shard_controller.go
> +//go:generate mockgen -copyright_file ../../../LICENSE -package $GOPACKAGE -source $GOFILE -destination shard_controller_mock.go
ditto

2022-11-14 22:40 UTC, rodrigozhou commented on service/history/definition/workflow_cache.go
> +//go:generate mockgen -copyright_file ../../../LICENSE -package $GOPACKAGE -source $GOFILE -destination workflow_cache_mock.go
ditto

2022-11-14 22:40 UTC, rodrigozhou commented on service/history/definition/workflow_context.go
> +//go:generate mockgen -copyright_file ../../../LICENSE -package $GOPACKAGE -source $GOFILE -destination workflow_context_mock.go
ditto

2022-11-14 23:01 UTC, wxing1292 commented
> Isn't `defs` more standard name for this instead of `definition`? No strong opinion though.

i have no opinions about `def` vs `definition`, what do you guys think?

2022-11-15 02:51 UTC, mindaugasrukas requested changes
Let's review this collectively. This change has a [code smell](https://en.wikipedia.org/wiki/Code_smell).

2022-11-15 03:01 UTC, mindaugasrukas commented
@wxing1292, please provide details where are `unnecessary go circular imports`. And if possible, please provide a full context of the issue and why the proposed solution should be acceptable.

IMO, this change should deserve an extensive design review.

2022-11-15 03:26 UTC, wxing1292 commented
> Let's review this collectively. This change has a [code smell](https://en.wikipedia.org/wiki/Code_smell).

i do not believe it is a good idea to simply block someone's PR to learn something or figure out a code.

>please provide details where are unnecessary go circular imports

simply google search can provide some info, e.g. https://stackoverflow.com/questions/28256923/import-cycle-not-allowed

2022-11-15 17:45 UTC, mindaugasrukas commented
Have we considered extracting the cache to a dedicated package?

2022-11-15 18:27 UTC, wxing1292 commented
> Have we considered extracting the cache to a dedicated package?

demo-ed offline, at least there is no easy solution right now.

2022-11-16 00:03 UTC, mindaugasrukas commented
Would this work https://github.com/temporalio/temporal/pull/3601?

2022-11-16 00:18 UTC, alexshtin requested changes
I don't like this change. It goes against basic go principles. Yes, we probably can't refactor entire code base and move interfaces on caller side right now. Or even get rid of interfaces where they are not really needed. But this is move in opposite direction.

The fact that you need such kind of package (`common`, `util`, `helpers`, `definition`, etc) indicates that code is not structured properly. And by proper structure, I mean small packages with well defined scope and responsibility. And again, I understand, that you don't have time to do it right now.

What is your immediate need? Can you do a minimum small change instead? And let's discuss long term plan around `service/history` refactoring.

2022-11-16 21:07 UTC, alexshtin commented
To support my point:
> Don’t use a single package for all your APIs. Many well-intentioned programmers put all the interfaces exposed by their program into a single package named `api`, `types`, or `interfaces`, thinking it makes it easier to find the entry points to their code base. This is a mistake. Such packages suffer from the same problems as those named `util` or `common`, growing without bound, providing no guidance to users, accumulating dependencies, and colliding with other imports. Break them up, perhaps using directories to separate public packages from implementation.

From: https://go.dev/blog/package-names.

2022-11-21 18:01 UTC, wxing1292 commented
>Yes, we probably can't refactor entire code base and move interfaces on caller side right now. 

can we ever?
how many callers for e.g. shard context? how many for mutable state? if we create the interface on the caller side, how many same / similar interfaces should we create & **manage** ? is this practical?

>Or even get rid of interfaces where they are not really needed.

name few interfaces which are not needed.
removing interfaces means making it harder to decoupling components, harder to write tests (no mocks)

>The fact that you need such kind of package (common, util, helpers, definition, etc) indicates that code is not structured properly. And by proper structure, I mean small packages with well defined scope and responsibility.

no idea why `common`, `util`, `helpers` are mentioned here, i am going to ignore.
the definition package is introduced here aiming to reduce the frequency of go circular imports (this issue is rather annoying)

imagine if you are a dev attempting to add a new feature

example 1:
before: package1 → package0
after: package1 → package0; `new logic: package0 → package1` ← import cycles

example 2:
before: package2 → package1; package1 → package0
after: package2 → package1; package1 → package0; `new logic: package0 → package2` ← import cycles

keeping the existing structure **may** still allow the open source server to survive for a long time, at the cost of dev continuing to moving logic around. 

what i proposed here (you should take a look at the internal doc) is to have a dedicated package for interface / struct definition, so concrete implementations only need to import this definition package. this decrease the possibility of go import cycles

>And again, I understand, that you don't have time to do it right now.

do you?

>What is your immediate need? Can you do a minimum small change instead? And let's discuss long term plan around service/history refactoring.

are you familiar with our persistence layer struct / interface definitions? if not, take a look. this PR pretty much does the same. 
if our persistence layer can do a decent job supporting Cassandra /  SQL (MySQL / PostgreSQL / SQLite) & other DBs use by our anonymous OSS users, then this PR should (begin to) allow more customizability as well 

>... thinking it makes it easier to find the entry points to their code base ...

this is not the intent, see above resp

2022-11-29 19:46 UTC, mindaugasrukas commented
> Let's review this collectively. This change has a [code smell](https://en.wikipedia.org/wiki/Code_smell).

I publicly apologize for my unprofessional comment about this change having a code smell.
Also, I'm unblocking this PR and leaving the decision to the repository owners.

As an alternative to this change, please consider https://github.com/temporalio/temporal/pull/3601.

2022-12-01 01:58 UTC, yycptt reviewed
There're a lot more in other files and tests. Plz double check.

2022-12-01 01:58 UTC, yycptt commented on service/history/ndc/activity_replicator.go
> +		definition.CallerTypeTask,
`CallerTypeAPI`

2022-12-01 01:58 UTC, yycptt commented on service/history/ndc/history_replicator.go
> +		definition.CallerTypeTask,
`CallerTypeAPI`

2022-12-01 01:58 UTC, yycptt commented on service/history/ndc/transaction_manager.go
> +		definition.CallerTypeTask,
`CallerTypeAPI`

2023-02-06 23:41 UTC, yiminc commented
Close this PR as we are not doing this for now.

2023-02-06 23:41 UTC, closed without merging