Introduce dynamic config rollout percentage for history branch operations
temporalio/temporal pull request #4266
Opened 2023-05-02 19:54 UTC by norberthu

**What changed?**

**Why?**
Prefactor for the following soon to be introduced history branch related RPC:
- ReadHistoryBranch
- ReadHistoryBranchReverse
- ReadRawHistoryBranch
- TrimHistoryBranch
- DeleteHistoryBranch

**How did you test it?**

**Potential risks**

**Is hotfix candidate?**

2023-05-02 21:25 UTC, norberthu commented on config/dynamicconfig/development-cass.yaml
> +  - value: 0.0
I used this during development to dial the traffic back and forth. I'll remove it from the PR

2023-05-03 00:07 UTC, MichaelSnowden requested changes

2023-05-03 00:07 UTC, MichaelSnowden commented on common/dynamicconfig/constants.go
> +	// FrontendReadEventsFromHistoryFraction (0.0~1.0) frontend calls to history for history branch related operations.
```suggestion
	// FrontendReadEventsFromHistoryFraction (0.0~1.0) is the fraction of history branch queries that are sent to the history service. Other queries hit the database directly.
```

2023-05-03 00:07 UTC, MichaelSnowden commented on service/frontend/adminHandler.go
>  		}
I don't think this should be committed--what happens if someone sets the dc to 100% in a later release and then rolls back to this one? Or, what if someone sets the DC to a non-zero number now? We should add the implementation first, then the DC branching

2023-05-03 20:45 UTC, MichaelSnowden approved these changes
LGTM after linter comment

2023-05-05 14:13 UTC, merged