Add the ability to implement and test custom advanced visibility stores
temporalio/temporal pull request #4871
Opened 2023-09-13 17:07 UTC by aromanovich

**What changed?**

Two things:
* `common/persistence/tests/visibility_persistence_suite_test.go` renamed to `visibility_persistence_suite.go`, so that its `VisibilityPersistenceSuite` could be imported and run by the third-party package;
* `VisibilityStoreFactory` interface introduced. The server now accepts `customVisibilityStoreFactory` and invokes it if visibility store configuration points to `CustomDataStoreConfig`.

**Why?**

To be have an ability to implement and test custom advanced visibility stores.

**How did you test it?**
Ran Temporal tests.
Also built and ran a Temporal server with `temporal.WithCustomVisibilityStoreFactory(mypackage.NewMyVisibilityStoreFactory())` option passed.

**Potential risks**
None.

**Is hotfix candidate?**
No.

2023-11-14 12:23 UTC, aromanovich commented
@rodrigozhou, does this feature seem acceptable in principle? If yes, I would rebase and resolve conflicts so we could proceed with the review.

2023-11-16 23:38 UTC, rodrigozhou commented
@aromanovich Yes, please. This feature sounds nice!

2023-11-17 21:40 UTC, aromanovich commented
@rodrigozhou, done.

I would greatly appreciate if you could also take a look at https://github.com/temporalio/temporal/pull/5118 — it's a bit related. Merging them would make the life of https://github.com/yandex/temporal-over-ydb a lot easier :)

2023-11-21 19:03 UTC, aromanovich commented
Gentle bump. Just in case this got lost 🙂

2023-11-21 22:07 UTC, rodrigozhou requested changes
LGTM, just added a nit comment.

2023-11-21 22:07 UTC, rodrigozhou commented on common/persistence/visibility/factory.go
> +		return nil, nil
`visStore` and `err` must be `nil` if it didn't enter any of those branches, so the last return should work.

2023-11-22 16:58 UTC, rodrigozhou approved these changes

2023-11-22 16:58 UTC, rodrigozhou commented
@aromanovich 
Approved, but it has conflicts with main branch again. Can you rebase it so I can merge please?

2023-11-22 18:47 UTC, aromanovich commented
@rodrigozhou Done. Semgrep is not passing, but I'm quite sure it's not due to my rebase :)

2023-11-22 22:23 UTC, merged