Rotation zap log
temporalio/temporal pull request #5231
Opened 2023-12-14 10:04 UTC by tuyenpthust

## What changed?
add rotation zaplog based on file size

## Why?
Currently all log are written in 1 file, it's easier to maintain, debug, backup if the log file is rotated

## How did you test it?
Test locally and unittest

2024-04-08 18:21 UTC, tdeebswihart commented on common/log/config.go
> +		// EnableRotation where file rotation is enabled. If this enabled, output file must be provided
```suggestion
EnableRotation specifies whether file rotation is enabled. If this enabled, the output file must be provided
```

2024-04-08 18:21 UTC, tdeebswihart commented on common/log/zap_logger.go
> +		core, _ := rotationZapCore(cfg, config)
We need to check and respond to this error, please don't swallow it

2024-04-08 18:21 UTC, tdeebswihart commented on common/log/zap_logger.go
> +	if name == "console" {
Would you mind replacing these with an enum containing something like `ConsoleEncoding` and `JSONEncoding` in the few places we use it?

2024-04-09 17:34 UTC, tdeebswihart commented on common/log/zap_logger_bench_test.go
> +	zLogger, _ := buildZapLogger(Config{Level: "info"}, false)
Please check these errors and fail the benchmarks if these fail. It will help prevent problems when this code changes in the future

2024-04-09 17:35 UTC, tdeebswihart commented on common/log/zap_logger_test.go
> +func TestNoRotationLogger(t *testing.T) {
Nit: how about
```suggestion
func TestLogger_FilesArentRotated_WhenDisabled(t *testing.T) {
```

That's cleared about what you're testing (and the above could be `TestLogger_FilesAreRotated_WhenEnabled` or something)

2024-04-09 17:36 UTC, tdeebswihart commented on proto/api
This shouldn't be updated as part of your PR. Please either rebase on main or check out the same version of the submodule as is on main

2024-04-09 17:57 UTC, dnr requested changes
I appreciate the contribution, but I'm wondering if this is really something that we want to build into the server, adding complexity and taking on yet another dependency.

In general modern infrastructure is moving in the direction of having server processes log to stdout, and having external systems accept logs and slice and dice and ship them in various ways, specifically so that every server doesn't have to have a full range of configuration options and log processing can be consolidated across services. This is true of both single-machine process managers like docker and systemd and of course distributed systems like k8s as well.

In that light, this change feels like a bit of a regression in infrastructure management. Could you provide a stronger justification for why this should go in the server itself?

2025-04-12 15:12 UTC, closed without merging