Migrate usage of metrics.Handler to metricDefinition.With
temporalio/temporal pull request #5435
Opened 2024-02-19 01:48 UTC by luansapelli

## What changed?
Using the new metricDefinition.With approach in the client package.

## Why?
The usage of metrics.Handler could be both redundant and unsafe:

```
 handler.Histogram( myHisto.Name(), myHisto.Unit() ).Record(...)
                │             │               └───┐
                │             │                   │
                └─────┐       └───────────┐       │
                      │                   │       │
       Redundant and Unsafe: 'Histogram'  │       │
       is specified despite knowing       │       │
       'myHisto' is a histogram. There's  │       │
       also a risk if 'myHisto.Name()'    │       │
       refers to a metric definition that │       │
       is not a histogram.                │       │
                                          └─── Redundant information
```

And using the new With(Handler) method, there's no need to specify redundant information.

## How did you test it?
Already exists an ExampleHandler which tests all the new approach methods.

## Potential risks
People can still use the old approach, because we are keeping the Handler interface as-is.

## Is hotfix candidate?
No.

2024-02-20 20:17 UTC, MichaelSnowden approved these changes

2024-02-20 20:23 UTC, MichaelSnowden requested changes
Oh, I actually see now that there are some test failures due to some changes removing usage of the `metrics.ContextCounterAdd` API. Could you please address those? We only want to remove direct usage of handler methods, not calls to some of the helper functions in the `metrics` package.

2024-02-22 18:07 UTC, ast2023 approved these changes
Thank you! 
Just a thought. IMHO another option for the API would be:
```
handler.Record(metrics.HistoryArchiverArchiveTransientErrorCount.add(1))
```
Not sure about `add`, may be `of`, or just `Count(1)`.
Probably a bigger change.

2024-03-07 22:54 UTC, MichaelSnowden approved these changes

2024-03-07 23:09 UTC, merged