Change namespace data to map<string, bytes>
temporalio/temporal pull request #5492
Opened 2024-03-05 19:35 UTC by tdeebswihart

## What changed?
The namespace data map now has `bytes` values rather than `string`.

## Why?
We embed binary data (cast to strings) here in a few places, and that can cause google/protobuf to yell at us for having string data that's invalid UTF-8. Protobuf strings and bytes are wire-compatible

## How did you test it?

## Potential risks
This will change all code generated by protoc plugins to use the language's type for raw bytes. I have paired Go API and server PRs that will go along with this change

## Documentation
None

## Is hotfix candidate?
no

2024-03-05 19:36 UTC, stephanos approved these changes

2024-03-05 22:40 UTC, yycptt approved these changes

2024-03-06 00:44 UTC, yiminc requested changes
Please hold on. This will be a compile time breaking change?

2024-03-06 01:17 UTC, yycptt commented
> Please hold on. This will be a compile time breaking change?

I think this server side change should be fine, and required for loading data back with the new proto library. 
Question is if the public api change is ok/needed or not.

2024-03-06 19:14 UTC, closed without merging