Fix sequence diagram rendering
temporalio/temporal pull request #5542
Opened 2024-03-15 07:09 UTC by gow

## What changed?
The sequence diagram rendering in [history service doc](https://github.com/temporalio/temporal/blob/main/docs/history-service.md) is broken. Looks like there is a redundant break tag `<br>` that is causing it to not render correctly.

## Why?

To fix the sequence diagram rendering.

## How did you test it?

Previewed the doc and verified that the diagram is rendered correctly.

## Potential risks

N/A

## Documentation

N/A

## Is hotfix candidate?

No

2024-03-15 14:03 UTC, dandavison commented
Hi @gow, I deliberately used two `<br>` tags there to add vertical separation between the annotation "thirty days elapses" and the event "timer fired", so that it was clear that they were two different concepts (as opposed to "the thirty day timer fired"). It's rendering correctly for me in VSCode and Chrome.

<img width="286" alt="image" src="https://github.com/temporalio/temporal/assets/52205/3d320a80-c480-4012-ab7a-3b5b834d7d3e">

2024-03-15 15:25 UTC, gow commented
Interesting. This is what I saw on Safari. I didn't verify in other browsers and assumed it's broken. Maybe something else is at play here. I'll take another look.
![Screenshot 2024-03-15 at 8 23 38 AM](https://github.com/temporalio/temporal/assets/1923995/e8242adf-2cd4-4d67-800b-61e6f0d40b8f)

2024-03-19 23:30 UTC, carlydf approved these changes
thanks!

2024-03-19 23:31 UTC, carlydf commented
> thanks!

oops actually I didn't see the safari screenshot you posted ..

2024-04-16 16:23 UTC, dandavison requested changes
Based on the discussion it sounded like more investigation was needed.

2024-06-05 16:34 UTC, closed without merging