fix(schema): check for extension before creating
temporalio/temporal pull request #7002
Opened 2024-12-17 22:23 UTC by ysdanielkim

## What changed?
`CREATE EXTENSION` sql query is replaced with a pgsql script that checks for the existence of the extension programatically.

## Why?
`CREATE EXTENSION` can cause issues in environment where creating extensions are limited to certain users. (e.g. Azure)

## How did you test it?
I've ran the updated schema setup in both environments where btree_gin is installed and and not installed.

## Potential risks
Regression in visibility database setup.

## Documentation
Not needed.

## Is hotfix candidate?
No

2025-02-24 19:41 UTC, jmbarzee commented
@ysdanielkim Thank you for bringing this up and submitting a PR no less!

I'm reviewing the changes and running them through our internal tests. I'm additionally reviewing how this may have got through our tests which test upgrade scenarios.

Can you tell me what version of Postgress you are running?

2025-02-24 19:42 UTC, rodrigozhou commented
@ysdanielkim I don't really understand why the script would make any difference here, you're still calling `CREATE EXTENSION`. Can you provide more details or references for this change? Also, did you verify it works in PostgreSQL 12 (min version supported by Temporal)?

2025-02-24 20:06 UTC, jmbarzee commented
To add to @rodrigozhou 's question: Its unclear what situation this addresses. Can you clarify what situation this addresses? 

Does it just ensure that the user can check if the extension already exists even if they don't have permission to install extensions?

2025-02-25 01:34 UTC, ysdanielkim commented
Of course. This addresses an issue in Azure PostgreSQL where non-admin users cannot create extensions. The extensions in the database are usually set up by a separate admin user and the application is not given admin rights to the database.

This error is returned by Azure PostgreSQL if `CREATE EXTENSION` is executed by a non-admin user:
```
ERROR: Only members of "azure_pg_admin" are allowed to use CREATE EXTENSION (SQLSTATE 42501)
```
And [here is the related documentation](https://learn.microsoft.com/en-us/azure/postgresql/extensions/how-to-create-extensions) from Azure.

Adding this conditional ensures that `CREATE EXTENSION` command is not executed when the extension is already present in the database.

And yes, I've tested this on non-azure PG12 as well.

2025-02-28 05:11 UTC, rodrigozhou commented
@ysdanielkim This doesn't seem that will solve anything. The script is for creating necessary table for running Temporal, and we need the extension for that. So, whoever is setting up the DB needs the required permission for running the entire script. The script is meant to be executed only once with the required permissions.

2025-09-25 03:14 UTC, ysdanielkim commented
@rodrigozhou Hmm. Looks like there's some issues with the build. Any idea what's going on?

2025-09-25 04:32 UTC, rodrigozhou commented
It seems it's failing in all PR's, some auth related issue. I'm looking into it.

2025-09-25 05:14 UTC, rodrigozhou commented
@ysdanielkim It seems that all tests with Postgres are failing. Please take a look at those

2025-09-25 15:17 UTC, ysdanielkim commented
@rodrigozhou this ready for another build.

2025-09-25 22:18 UTC, rodrigozhou commented on common/persistence/query_util.go
> +					if hasWordAt(contentStr, sqlEndIfKeyword, j) {
I wonder if this would work if there were more than a single space (eg: `end   if`).

2025-09-25 22:26 UTC, ysdanielkim commented on common/persistence/query_util.go
> +					if hasWordAt(contentStr, sqlEndIfKeyword, j) {
I don't think it'll work. Do you find the it important? I'd be happy to accommodate if you think so.

2025-09-25 22:29 UTC, rodrigozhou commented on common/persistence/query_util.go
> +					if hasWordAt(contentStr, sqlEndIfKeyword, j) {
Yes, I think it would good to have it work properly if possible.

2025-09-26 05:00 UTC, ysdanielkim commented on common/persistence/query_util.go
> +					if hasWordAt(contentStr, sqlEndIfKeyword, j) {
https://github.com/temporalio/temporal/pull/7002/commits/be320fa092c07d55cd481f105d6898379525f817

2025-09-26 17:09 UTC, rodrigozhou requested changes

2025-09-26 17:09 UTC, rodrigozhou commented on common/persistence/query_util.go
> +							j = after + len(sqlIfKeyword)
Need to subtract 1, right?
```suggestion
							j = after + len(sqlIfKeyword) - 1
```

2025-09-26 18:08 UTC, ysdanielkim commented on common/persistence/query_util.go
> +							j = after + len(sqlIfKeyword)
Yes. Thanks.

2025-09-27 04:47 UTC, ysdanielkim commented
> Please fix the lint errors. Otherwise, LGTM

@rodrigozhou Fixed. Thanks for your help.

2025-09-29 18:02 UTC, merged